WBSAtool/WBSAtool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('backend.urls')),
    path('', include('frontend.urls'))
]

WBSAtool/backend/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views
from backend import views

app_name = 'backend'
urlpatterns = [
    path('area', views.AreaList.as_view()),
    path('area/<int:pk>', views.AreaDetail.as_view()),
    path('area/<int:pk>/timeslots', views.TimeslotCount.as_view()),
    path('street', views.StreetList.as_view()),
    path('street/<int:pk>', views.StreetDetail.as_view()),
    path('timeslot', views.TimeslotList.as_view()),
    path('timeslot/<int:pk>', views.TimeslotDetail.as_view()),
    path('timeslot/<int:pk>/count', views.singleTimeslotCount.as_view()),
    path('appointment', views.AppointmentList.as_view()),
    path('appointment/<int:pk>', views.AppointmentDetail.as_view()),
    path('api-token-auth/', drf_views.obtain_auth_token)
]

WBSAtool/frontend/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views, auth_views
from .view_collection.area import AreaListView, AreaCreateView, AreaUpdateView
from .view_collection.street import StreetListView, StreetCreateView, StreetUpdateView, StreetBulkUpdateView
from .view_collection.timeslot import TimeslotListView, TimeslotCreateView, TimeslotUpdateView
from .view_collection.appointment import AppointmentListView, AppointmentDispoView, UpdateAppointmentCollected, AppointmentMapView, AppointmentStatsView
from .view_collection.collect import CollectMenu, CollectList

app_name = 'frontend'
urlpatterns = [
    path('', RedirectView.as_view(url='appointment/map'), name='index'),
    path('area/list', AreaListView.as_view(), name='area_list'),
    path('area/new', AreaCreateView.as_view(), name='area_new'),
    path('area/delete', views.area_delete, name='area_delete'),
    path('area/<int:area_id>', views.area_view, name='area_view'),
    path('area/<int:pk>/edit', AreaUpdateView.as_view(), name='area_edit'),
    path('street/list', StreetListView.as_view(), name='street_list'),
    path('street/new', StreetCreateView.as_view(), name='street_new'),
    path('street/edit', StreetBulkUpdateView.as_view(), name='street_bulk_edit'),
    path('street/delete', views.street_delete, name='street_delete'),
    path('street/bulkadd', views.street_bulkadd, name='street_bulkadd'),
    path('street/osm_import', views.street_osm_import, name='street_osm_import'),
    path('street/<int:pk>/edit', StreetUpdateView.as_view(), name='street_edit'),
    path('timeslot/list', TimeslotListView.as_view(), name='timeslot_list'),
    path('timeslot/delete', views.timeslot_delete, name='timeslot_delete'),
    path('timeslot/new', TimeslotCreateView.as_view(), name='timeslot_new'),
    path('timeslot/<int:pk>/edit', TimeslotUpdateView.as_view(), name='timeslot_edit'),
    path('timeslot/suggestion', views.timeslot_suggestion, name='timeslot_suggestion'),
    path('appointment/list', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/dispo', AppointmentDispoView.as_view(), name='appointment_dispo'),
    path('appointment/pdf', views.generate_pdf, name='appointment_pdf'),
    path('appointment/bulk', views.appointment_bulk, name='appointment_bulk'),
    path('appointment/map', AppointmentMapView.as_view(), name='appointment_map'),
    path('appointment/stats', AppointmentStatsView.as_view(), name='appointment_stats'),
    path('appointment/new', views.appointment_new, name='appointment_new'),
    path('appointment/<int:appointment_id>', views.appointment_view, name='appointment_view'),
    path('appointment/<int:appointment_id>/edit', views.appointment_edit, name='appointment_edit'),
    path('appointment/<int:appointment_id>/collected', UpdateAppointmentCollected.as_view()),
    path('appointment/<int:appointment_id>/clearOverwrite', views.appointment_overwrite_remove, name='appointment_clearOverwrite'),
    path('mobile/menu', CollectMenu.as_view(), name='collect_menu'),
    path('mobile/list', CollectList.as_view(), name='collect_list'),
    path('auth/login', auth_views.login_user, name='login'),
    path('auth/logout', auth_views.logout_user, name='logout')
]

WBSAtool/backend/models.py
import requests
from time import sleep
from django.db import models

from backend import logger
from WBSAtool.settings import NOMINATIM_URL

class Area(models.Model):
    name = models.CharField(max_length=200)
    is_parent = models.BooleanField(default=False)
    parent = models.ForeignKey('Area',
                               limit_choices_to={'is_parent': True},
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True)

    def __str__(self):
        return self.name

    def get_timeslots(self):
        if not self.is_parent:
            return []
        logger.error(f"Area {self.name} has no parent, returning empty Timeslot List")
        list = []
        for ts in Timeslot.objects.order_by("date", "time_from"):
            list.append({"area": self,
                "timeslot":ts,
                "appointment_max":ts.appointment_max,
                "count":ts.get_count_per_area(self.id),
                "percentage":ts.get_percentage_per_area(self.id)})
        return list


class Street(models.Model):
    name = models.CharField(max_length=200)
    area = models.ForeignKey('Area',
                             limit_choices_to={'is_parent': False},
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    osm_imported = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Timeslot(models.Model):
    date = models.DateField()
    time_from = models.TimeField()
    time_to = models.TimeField()
    appointment_max = models.IntegerField()

    def __str__(self):
        return f"{self.date}_{self.time_from}_{self.time_to}"

    def get_count_per_area(self, area_id):
        qs = Appointment.objects.filter(timeslot=self, street__area__parent_id=area_id, area__isnull=True)
        overwrites = Appointment.objects.filter(timeslot=self, area_id=area_id)
        count = (qs | overwrites).count()
        return count

    def get_percentage_per_area(self, area_id):
        percentage = 100 / self.appointment_max * self.get_count_per_area(area_id)
        return percentage

    def get_all_percentage(self):
        list = []
        for area in Area.objects.filter(is_parent=True):
            list.append({"id":area.id, "name":area.name,
                         "percentage":self.get_percentage_per_area(area.id),
                         "count":self.get_count_per_area(area.id)})
        return list


class Appointment(models.Model):
    is_collected = models.BooleanField(default=False)
    area = models.ForeignKey('Area',
                             default=None,
                             on_delete=models.SET_NULL,
                             null=True)
    contact_name = models.CharField(max_length=200)
    street = models.ForeignKey('Street',
                               on_delete=models.CASCADE,
                               null=True)
    house_number = models.CharField(max_length=200)
    timeslot = models.ForeignKey('Timeslot',
                                 on_delete=models.CASCADE,
                                 null=True)
    text = models.CharField(max_length=2000,
                            blank=True,
                            default="")
    phone = models.CharField(max_length=200,
                             blank=True)
    email = models.CharField(max_length=200,
                             blank=True)
    lat = models.CharField(max_length=200,
                             blank=True)
    lon = models.CharField(max_length=200,
                             blank=True)

    def __str__(self):
        return f"{self.contact_name}, {self.street.name} {self.house_number}"

    def save(self, *args, **kwargs):
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
        params = {
            "street": f"{self.street} {self.house_number}",
            "city": "Karlsruhe",
            "postalcode": "76227",
            "format": "jsonv2"
        }
        for i in range(1,5):
            try:
                r = requests.get(NOMINATIM_URL, params=params, headers=headers)
                if r.status_code != 200:
                    logger.error(f"encountered Error {r.status_code} while getting data from nominatim")
                    logger.error(r.text)
                    break
                result = r.json()[0]
                if "lat" in result:
                    self.lat = result['lat']
                    self.lon = result['lon']
                    break
                else:
                    logger.info(f"No latitude data in Response, trying again")
                    sleep(1)
            except Exception as e:
                logger.error(e, stack_info=True)
                sleep(1)
        super(Appointment, self).save(*args, **kwargs)

WBSAtool/frontend/forms.py
from django import forms
from backend.models import Area, Street, Timeslot
from django.forms.models import ModelChoiceField

class TimeslotChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.date}, {str(obj.time_from)[:-3]} bis {str(obj.time_to)[:-3]}"


class CollectMenuForm(forms.Form):
    area = forms.ModelChoiceField(queryset=Area.objects.filter(is_parent=True),
                                  label="Fahrzeug",
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    timeslot = TimeslotChoiceField(queryset=Timeslot.objects.all(),
                                   label="Zeitraum",
                                   widget=forms.Select(attrs={'class': 'form-select'}))


class StreetForm(forms.ModelForm):
    class Meta:
        model = Street
        exclude = ["osm_imported"]
        titel = "Straße"
    name = forms.CharField(label="Straßenname",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))


class BulkUpdateStreetForm(forms.Form):
    class Meta:
        titel = "mehrere Straßen bearbeiten"
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    select_row = forms.ModelMultipleChoiceField(queryset=Street.objects.all(),
                                                widget=forms.MultipleHiddenInput)


class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        exclude = []
        titel = "Gebiet"
    name = forms.CharField(label="Name",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_parent = forms.BooleanField(label="Ist ein Fahrzeug",
                                   required=False,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    parent = forms.ModelChoiceField(label="Fahrzeug",
                                    required=False,
                                    queryset=Area.objects.filter(is_parent=True),
                                    widget=forms.Select(attrs={'class': 'form-select'}))


class TimeslotForm(forms.ModelForm):
    class Meta:
        model = Timeslot
        exclude = ["appointment_count", "is_full"]
        titel = "Abholzeitraum"
    date = forms.DateField(label="Datum",
                           widget=forms.DateInput(attrs={'class': 'form-control w-auto', 'type': 'date'}))
    time_from = forms.TimeField(label="Beginn",
                                widget=forms.TimeInput(format='%H:%M',
                                                       attrs={'class': 'form-control w-auto', 'type': 'time'}))
    time_to = forms.TimeField(label="Ende",
                              widget=forms.TimeInput(format='%H:%M',
                                                     attrs={'class': 'form-control w-auto', 'type': 'time'}))
    appointment_max = forms.IntegerField(label="Maximale Abholungen",
                                         widget=forms.TextInput(attrs={'class': 'form-control w-auto'}))

WBSAtool/frontend/templates/appointment/appointment_edit.html
{% extends 'base.html' %}

{% block titel %}Termin zur Abholung{% endblock titel %}

{% block container %}
<div class="container-fluid p-5">
<div class="row">
    <div class="col-6" name="map-col">
        <div id="map" style="width: 100%; height: 100%;"></div>
    </div>
    <div class="col-6" name="form-col">
{% if appointment.id %}
    <form autocomplete="off" action="{% url 'frontend:appointment_edit' appointment.id %}" method="post" class="form-object-edit">
{% else %}
    <form autocomplete="off" action="{% url 'frontend:appointment_new' %}" method="post" class="form-object-edit">
{% endif %}
        {% csrf_token %}
            <div class="field-group my-5">
                <div class="row mb-3">
                    <div class="col-sm-3"></div>
                    <div class="col">
                    <h5 class="">Kontaktdaten</h5>
                    </div>
                </div>
	            <div class="row mb-3">
                    <label for="name" class="col-sm-3 col-form-label text-lg-end">Name*</label>
                    <div class="col">
                        <input type="text" name="name" value="{{ appointment.contact_name }}" maxlength="64" class="form-control" placeholder="Name auf Klingelschild" id="name" required>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="street" class="col-sm-3 col-form-label text-lg-end">Straße*</label>
                    <div class="col autocomplete">
                        <input type="text" name="street" value="{{ appointment.street }}" class="form-control" id="street" placeholder="Straße" autocomplete="off" required>
                        <script>
                            const nominatim_url = "{{ NOMINATIM_URL }}";
                            const streets = [{% for street in street_list %}"{{street.name}}",{% endfor %}];
                            autocomplete(document.getElementById("street"), streets);
                        </script>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="house_number" class="col-sm-3 col-form-label text-lg-end">Hausnummer*</label>
                    <div class="col">
                        <input type="text" name="house_number" value="{{ appointment.house_number }}" maxlength="64" class="form-control" placeholder="Hausnummer" id="house_number" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="phone" class="col-sm-3 col-form-label text-lg-end">Telefon</label>
                    <div class="col">
                        <input type="text" name="phone" value="{{ appointment.phone }}" maxlength="64" class="form-control" placeholder="Telefon-Nummer" id="phone">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="email" class="col-sm-3 col-form-label text-lg-end">EMail</label>
                    <div class="col">
                        <input type="text" name="email" value="{{ appointment.email }}" maxlength="64" class="form-control" placeholder="E-Mail Adresse" id="email">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="text" class="col-sm-3 col-form-label text-lg-end">zusätzliche Informationen</label>
                    <div class="col">
                        <textarea name="text" rows="5" class="form-control" placeholder="Informationen wo der Baum liegt, wie die Tür zu finden ist, etc." id="text">{{ appointment.text }}</textarea>
                    </div>
                </div>
            </div>
            <div class="field-group my-5">
                <div class="row mb-3">
                    <div class="col-sm-3"></div>
                    <div class="col">
                    <h5 class="">Abholung</h5>
                    </div>
                </div>
                <div id="suggestion_list"></div>
                <div class="row mb-3">
                    <label for="timeslot" class="col-sm-3 col-form-label text-lg-end">Zeitslot*</label>
                    <div class="col">
                        <select class="form-select" name="timeslot" id="timeslot" required>
                            {% if appointment %}
                            {% for ts in timeslot_list %}
                                <option value="{{ts.timeslot.id}}" {%if appointment.timeslot.id == ts.timeslot.id %}selected{%endif%} {% if ts.percentage >= 100 %} disabled {% endif %}>
                                {{ts.timeslot.date}}, {{ts.timeslot.time_from|date:"H:i"}} bis {{ts.timeslot.time_to|date:"H:i"}} - {% if ts.percentage >= 100 %}AUSGEBUCHT!{% else %}Auslastung: {{ ts.count }}/{{ ts.appointment_max }}{% endif %}
                            </option>
                            {% endfor %}
                            {% endif %}
                        </select>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="timeslot" class="col-sm-3 col-form-label text-lg-end">Fahrzeug überschreiben</label>
                    <div class="col">
                        <select class="form-select" name="area" id="area">
                            <option value="None">--- kein Overwrite ---</option>
                            {% for area in area_list %}
                                <option value="{{ area.id }}" {% if appointment.area.id == area.id %}selected{% endif %}>{{ area.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="text-end my-3">
                        <button type="submit" name="update" class="btn btn-primary">Speichern</button>
                        {% if appointment %}
                            <a class="btn btn-outline-danger" href="{% url 'frontend:appointment_list' %}">Abbrechen</a>
                        {% else %}
                            <a class="btn btn-outline-danger" href="{% url 'frontend:appointment_new' %}">Reset</a>
                        {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock container %}
{% load static %}
{% block head %}
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
<link rel="stylesheet" href="/static/leaflet.extra-markers.min.css">
<script src="{% static 'wbsa_map.js' %}"></script>
{% endblock head %}

{% block jsfooter %}
 <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">

<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<script src="/static/leaflet.extra-markers.js"></script>
<script>
loadAppointmentMap();
</script>
{% endblock jsfooter%}

WBSAtool/frontend/templates/appointment/appointment_list.html
{% extends 'base.html' %}

{% block titel %}Abholungen{% endblock titel %}

{% block data %}

{% if appointment_list %}
<form method="post" action="{% url 'frontend:appointment_bulk' %}" class="my-md-3">
{% csrf_token %}
<table class="table">
    <thead class="table-dark">
        <tr>
            <th><input type="checkbox" class="toggle form-check-input" name="select_all"></th>
            <th>Name <div name="filter-col"></div></th>
            <th>Straße <div name="filter-col"></div></th>
            <th>Uhrzeit</th>
            <th>Abgeholt</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <div name="appointment_view_type" id="list" style="display: none;"></div>
    {% for appointment in appointment_list %}
        {% if appointment.lat == None %}
        <tr class="table-warning">
        {% else %}
        <tr>
        {% endif %}
            <td><input type="checkbox" class="toggle form-check-input" value="{{appointment.id}}" name="select_row"></td>
            <td>{{appointment.contact_name}}</td>
            <td>
                {{appointment.street}}
            {% if appointment.area %}
                <span class="badge bg-primary" id="badge_{{ appointment.id }}">Fzg überschrieben <button type="button" class="btn-close" onclick="clearOverwrite({{ appointment.id }})"></button></span>
            {% endif %}
            </td>
            <td>{{appointment.timeslot.date}}, {{appointment.timeslot.time_from|date:"H:i"}}-{{appointment.timeslot.time_to|date:"H:i"}}</td>
            <td id="status_{{appointment.id}}">
                {% if appointment.is_collected %}
                    <i class="bi bi-check-circle-fill text-success"></i>
                {% else %}
                    <i class="bi bi-x-circle-fill text-danger"></i>
                {% endif %}
            </td>
            <td class="noprint text-end text-nowrap">
                <a class="btn btn-sm btn-success" type="button" onclick="showAppointmentDetails({{appointment.id}})">
                    <i class="bi bi-info-circle"></i>
                </a>
                <a class="btn btn-sm btn-warning" href="{% url 'frontend:appointment_edit' appointment.id %}" type="button">
                    <i class="bi bi-pencil-square"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
    <button type="submit" name="action" value="delete" class="btn btn-danger btn-sm"><i class="bi bi-trash3"></i> Abholungen löschen</button>
    <button type="submit" name="action" value="clearOverwrite" class="btn btn-info btn-sm"><i class="bi bi-x-circle"></i> Overwrites entfernen</button>
    <a href="{% url 'frontend:appointment_pdf' %}" target="_blank" class="btn btn-primary btn-sm"><i class="bi bi-filetype-pdf"></i> PDF generieren</a>
    <a href="{% url 'frontend:appointment_dispo' %}" type="button" class="btn btn-sm btn-primary"><i class="bi bi-arrow-left-right"></i> Dispo-Ansicht</a>
</form>

<div id="appointment_modal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-xl">
        <div class="modal-content" id="appointment_detail">
        </div>
    </div>
</div>
{% else %}
Keine Abholungen angelegt!
{% endif %}
{% endblock data %}
{%  block jsfooter %}
<script>
document.addEventListener('DOMContentLoaded', () => {
    const params = new URLSearchParams(window.location.search);
    const appointmentID = params.get("id");
    if (!isNaN(appointmentID) && appointmentID != null && appointmentID != "") {
        showAppointmentDetails(appointmentID);
    }
});
</script>
{% endblock %}

WBSAtool/frontend/templates/appointment/appointment_modal.html
<div class="modal-header">
    <h5 class="modal-title">Details der Abholung</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>
<div class="modal-body">
    {% if appointment.area %}<span class="badge bg-primary my-2">Fahrzeug überschrieben</span>{% endif %}
    <ul class="list-group w-100">
        <li class="list-group-item list-group-item-action">
        {% if appointment.is_collected %}
            Abgeholt: Ja
        {% else %}
            Abgeholt: Nein
        {% endif %}
        </li>
        <li class="list-group-item list-group-item-action">Name: {{appointment.contact_name}}</li>
        <li class="list-group-item list-group-item-action">
            Adresse: <a href="http://www.google.com/maps/place/{{ appointment.lat }},{{ appointment.lon }}">{{appointment.street}} {{appointment.house_number}}</a>
        </li>
        <li class="list-group-item list-group-item-action">Telefon: {{appointment.phone}}</li>
        <li class="list-group-item list-group-item-action">EMail-Adresse: <a href="mailto:{{appointment.email}}">{{appointment.email}}</a></li>
        <li class="list-group-item list-group-item-action">Abholung: {{appointment.timeslot.date}}, Zwischen {{appointment.timeslot.time_from|date:"H:i"}} und {{appointment.timeslot.time_to|date:"H:i"}} Uhr</li>
        <li class="list-group-item list-group-item-action">Zusatz-Infos: {{appointment.text}}</li>
    </ul>
</div>
    <div class="modal-footer">
    {% if perms.backend.add_appointment %}
        <a class="btn btn-warning" href="{% url 'frontend:appointment_edit' appointment.id %}" type="button">
            <i class="bi bi-pencil-square"></i> Bearbeiten
        </a>
    {% endif %}
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="ModalCloseButton">Cancel</button>
        {% if appointment.is_collected %}
            <button type="button" class="btn btn-warning" onclick="markCollected(this, {{ appointment.id }})" value="false" id="MarkCollectedButton">Abholung offen</button>
        {% else %}
            <button type="button" class="btn btn-primary" onclick="markCollected(this, {{ appointment.id }})" value="true" id="MarkCollectedButton">Baum abgeholt</button>
        {% endif %}
    </div>

WBSAtool/frontend/templates/appointment/map.html
{% extends 'base.html' %}

{% block head %}
{% load static %}
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
<script src="{% static 'wbsa_map.js' %}"></script>
{% endblock head %}

{% block jsfooter %}
 <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css">

<script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<script src="/static/leaflet.extra-markers.js"></script>
<script>
loadGenericMap();
</script>
{% endblock jsfooter%}

{% block data %}
<div id="map" style="width: 100%; height: 750px"></div>
{% endblock data %}