WBSAtool/WBSAtool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('backend.urls')),
    path('', include('frontend.urls'))
]

WBSAtool/backend/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views
from backend import views

app_name = 'backend'
urlpatterns = [
    path('area', views.AreaList.as_view()),
    path('area/<int:pk>', views.AreaDetail.as_view()),
    path('area/<int:pk>/timeslots', views.TimeslotCount.as_view()),
    path('street', views.StreetList.as_view()),
    path('street/<int:pk>', views.StreetDetail.as_view()),
    path('timeslot', views.TimeslotList.as_view()),
    path('timeslot/<int:pk>', views.TimeslotDetail.as_view()),
    path('timeslot/<int:pk>/count', views.singleTimeslotCount.as_view()),
    path('appointment', views.AppointmentList.as_view()),
    path('appointment/<int:pk>', views.AppointmentDetail.as_view()),
    path('api-token-auth/', drf_views.obtain_auth_token)
]

WBSAtool/frontend/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views, auth_views
from .view_collection.area import AreaListView, AreaCreateView, AreaUpdateView
from .view_collection.street import StreetListView, StreetCreateView, StreetUpdateView, StreetBulkUpdateView
from .view_collection.timeslot import TimeslotListView, TimeslotCreateView, TimeslotUpdateView
from .view_collection.appointment import AppointmentListView, AppointmentDispoView, UpdateAppointmentCollected, AppointmentMapView, AppointmentStatsView
from .view_collection.collect import CollectMenu, CollectList

app_name = 'frontend'
urlpatterns = [
    path('', RedirectView.as_view(url='appointment/map'), name='index'),
    path('area/list', AreaListView.as_view(), name='area_list'),
    path('area/new', AreaCreateView.as_view(), name='area_new'),
    path('area/delete', views.area_delete, name='area_delete'),
    path('area/<int:area_id>', views.area_view, name='area_view'),
    path('area/<int:pk>/edit', AreaUpdateView.as_view(), name='area_edit'),
    path('street/list', StreetListView.as_view(), name='street_list'),
    path('street/new', StreetCreateView.as_view(), name='street_new'),
    path('street/edit', StreetBulkUpdateView.as_view(), name='street_bulk_edit'),
    path('street/delete', views.street_delete, name='street_delete'),
    path('street/bulkadd', views.street_bulkadd, name='street_bulkadd'),
    path('street/osm_import', views.street_osm_import, name='street_osm_import'),
    path('street/<int:pk>/edit', StreetUpdateView.as_view(), name='street_edit'),
    path('timeslot/list', TimeslotListView.as_view(), name='timeslot_list'),
    path('timeslot/delete', views.timeslot_delete, name='timeslot_delete'),
    path('timeslot/new', TimeslotCreateView.as_view(), name='timeslot_new'),
    path('timeslot/<int:pk>/edit', TimeslotUpdateView.as_view(), name='timeslot_edit'),
    path('timeslot/suggestion', views.timeslot_suggestion, name='timeslot_suggestion'),
    path('appointment/list', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/dispo', AppointmentDispoView.as_view(), name='appointment_dispo'),
    path('appointment/pdf', views.generate_pdf, name='appointment_pdf'),
    path('appointment/bulk', views.appointment_bulk, name='appointment_bulk'),
    path('appointment/map', AppointmentMapView.as_view(), name='appointment_map'),
    path('appointment/stats', AppointmentStatsView.as_view(), name='appointment_stats'),
    path('appointment/new', views.appointment_new, name='appointment_new'),
    path('appointment/<int:appointment_id>', views.appointment_view, name='appointment_view'),
    path('appointment/<int:appointment_id>/edit', views.appointment_edit, name='appointment_edit'),
    path('appointment/<int:appointment_id>/collected', UpdateAppointmentCollected.as_view()),
    path('appointment/<int:appointment_id>/clearOverwrite', views.appointment_overwrite_remove, name='appointment_clearOverwrite'),
    path('mobile/menu', CollectMenu.as_view(), name='collect_menu'),
    path('mobile/list', CollectList.as_view(), name='collect_list'),
    path('auth/login', auth_views.login_user, name='login'),
    path('auth/logout', auth_views.logout_user, name='logout')
]

WBSAtool/frontend/forms.py
from django import forms
from backend.models import Area, Street, Timeslot
from django.forms.models import ModelChoiceField

class TimeslotChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.date}, {str(obj.time_from)[:-3]} bis {str(obj.time_to)[:-3]}"


class CollectMenuForm(forms.Form):
    area = forms.ModelChoiceField(queryset=Area.objects.filter(is_parent=True),
                                  label="Fahrzeug",
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    timeslot = TimeslotChoiceField(queryset=Timeslot.objects.all(),
                                   label="Zeitraum",
                                   widget=forms.Select(attrs={'class': 'form-select'}))


class StreetForm(forms.ModelForm):
    class Meta:
        model = Street
        exclude = ["osm_imported"]
        titel = "Straße"
    name = forms.CharField(label="Straßenname",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))


class BulkUpdateStreetForm(forms.Form):
    class Meta:
        titel = "mehrere Straßen bearbeiten"
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    select_row = forms.ModelMultipleChoiceField(queryset=Street.objects.all(),
                                                widget=forms.MultipleHiddenInput)


class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        exclude = []
        titel = "Gebiet"
    name = forms.CharField(label="Name",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_parent = forms.BooleanField(label="Ist ein Fahrzeug",
                                   required=False,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    parent = forms.ModelChoiceField(label="Fahrzeug",
                                    required=False,
                                    queryset=Area.objects.filter(is_parent=True),
                                    widget=forms.Select(attrs={'class': 'form-select'}))


class TimeslotForm(forms.ModelForm):
    class Meta:
        model = Timeslot
        exclude = ["appointment_count", "is_full"]
        titel = "Abholzeitraum"
    date = forms.DateField(label="Datum",
                           widget=forms.DateInput(attrs={'class': 'form-control w-auto', 'type': 'date'}))
    time_from = forms.TimeField(label="Beginn",
                                widget=forms.TimeInput(format='%H:%M',
                                                       attrs={'class': 'form-control w-auto', 'type': 'time'}))
    time_to = forms.TimeField(label="Ende",
                              widget=forms.TimeInput(format='%H:%M',
                                                     attrs={'class': 'form-control w-auto', 'type': 'time'}))
    appointment_max = forms.IntegerField(label="Maximale Abholungen",
                                         widget=forms.TextInput(attrs={'class': 'form-control w-auto'}))

WBSAtool/frontend/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse
from django.contrib.auth.decorators import permission_required
import requests

from backend.models import Area, Street, Timeslot, Appointment
from backend.serializers import TimeslotCountSerializer
from .utils.ReportLabWrapper import ReportLab, wrap_text
from WBSAtool.settings import NOMINATIM_URL

@permission_required("backend.delete_area", raise_exception=True)
def area_delete(request):
    if request.method == 'POST':
        if request.POST['action'] == "delete_areas":
            for id in request.POST.getlist('select_row'):
                Area.objects.get(id=int(id)).delete()
            return HttpResponseRedirect(reverse('frontend:area_list'))
        elif request.POST['action']:
            id = int(request.POST['action'])
            Area.objects.get(id=id).delete()
            return HttpResponseRedirect(reverse('frontend:area_list'))


@permission_required("backend.view_area", raise_exception=True)
def area_view(request, area_id):
    if request.GET['format'] == "modal":
        area = get_object_or_404(Area, id=area_id)
        if area.is_parent:
            AreaList = Area.objects.filter(parent=area)
            StreetList = []
            for subarea in AreaList:
                l = Street.objects.filter(area=subarea)
                for street in l:
                    StreetList.append(street)
        else:
            StreetList = Street.objects.filter(area=area)
        context = {'area': area, 'street_list': StreetList}
        return render(request, 'area/area_modal.html', context)
    else:
        return HttpResponse("Error, only intended von indirect use")


@permission_required("backend.delete_street", raise_exception=True)
def street_delete(request):
    if request.method == 'POST':
        if request.POST['action'] == "delete":
            for id in request.POST.getlist('select_row'):
                Street.objects.get(id=int(id)).delete()
            return HttpResponseRedirect(reverse('frontend:street_list'))


@permission_required("backend.add_street", raise_exception=True)
def street_bulkadd(request):
    if request.method == 'GET':
        return render(request, 'street/street_bulk_add.html')
    if request.method == 'POST':
        ImportList = request.POST['data'].split("\r\n")
        header_raw = ImportList.pop(0)
        header = header_raw.split(",")
        if (header[0] == "street") and (header[1] == "area"):
            for line in ImportList:
                street = line.split(",")[0]
                newStreet = Street(name=street)
                if len(line.split(",")) > 1:
                    try:
                        area_name = line.split(",")[1]
                        AreaObject = Area.objects.get(name=area_name)
                        newStreet.area = AreaObject
                    except Area.DoesNotExist as e:
                        pass
                newStreet.save()
            return HttpResponseRedirect(reverse('frontend:street_list'))
        else:
            error_message = f"Falscher CSV-Header: {header_raw}"
            context = {"error_message": error_message}
            return render(request, "error_page.html", context)


@permission_required("backend.delete_timeslot", raise_exception=True)
def timeslot_delete(request):
    if request.method == 'POST':
        if request.POST['action'] == "delete":
            for id in request.POST.getlist('select_row'):
                Timeslot.objects.get(id=int(id)).delete()
            return HttpResponseRedirect(reverse('frontend:timeslot_list'))


@permission_required("backend.add_appointment", raise_exception=True)
def timeslot_suggestion(request):
    street = get_object_or_404(Street, name=request.GET['street'])
    TimeslotList = Timeslot.objects.all()
    SuggestionList = []
    for Slot in TimeslotList:
        count = Appointment.objects.filter(timeslot=Slot, street=street).count()
        if Slot.appointment_max == count:
            continue
        if count != 0:
            suggestion = {"timeslot": Slot, "count": count}
            SuggestionList.append(suggestion)
    if len(SuggestionList) == 0:
        return HttpResponse("")
    context = {"suggestion_list": SuggestionList}
    return render(request, "timeslot/timeslot_suggestion.html", context)


@permission_required(["backend.delete_appointment","backend.change_appointment"], raise_exception=True)
def appointment_bulk(request):
    if request.method == "POST":
        if request.POST['action'] == "delete":
            for id in request.POST.getlist('select_row'):
                Appointment.objects.get(id=int(id)).delete()
            return HttpResponseRedirect(reverse('frontend:appointment_list'))
        if request.POST['action'] == "clearOverwrite":
            for id in request.POST.getlist('select_row'):
                Appointment.objects.filter(id=int(id)).update(area=None)
            return HttpResponseRedirect(reverse('frontend:appointment_list'))


@permission_required("backend.view_appointment", raise_exception=True)
def appointment_view(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.GET['format'] == "modal":
        context = {'appointment': appointment}
        return render(request, 'appointment/appointment_modal.html', context)


@permission_required("backend.change_appointment", raise_exception=True)
def appointment_edit(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    if request.method == 'GET':
        StreetList = Street.objects.order_by("name")
        AreaList = Area.objects.filter(is_parent=True)
        if (appointment.street.area) and (appointment.street.area.parent) :
            TimeslotList = Area.objects.get(id=appointment.street.area.parent.id).get_timeslots()
        else:
            TimeslotList = [{"timeslot":appointment.timeslot,
                            "appointment_max":appointment.timeslot.appointment_max,
                            "count":"X",
                            "percentage":"X%"}]
        context = {"appointment": appointment, "street_list": StreetList, 'timeslot_list': TimeslotList, 'area_list': AreaList, 'NOMINATIM_URL': NOMINATIM_URL}
        return render(request, 'appointment/appointment_edit.html', context)
    if request.method == "POST":
        appointment.contact_name = request.POST['name']
        appointment.street = get_object_or_404(Street, name=request.POST['street'])
        appointment.house_number = request.POST['house_number']
        appointment.timeslot = get_object_or_404(Timeslot, id=request.POST['timeslot'])
        appointment.text = request.POST['text']
        appointment.phone = request.POST['phone']
        appointment.email = request.POST['email']
        if request.POST['area'] != "None":
            appointment.area = Area.objects.get(id=request.POST['area'])
        else:
            appointment.area = None
        appointment.save()
        return HttpResponseRedirect(reverse('frontend:appointment_list'))


@permission_required("backend.add_appointment", raise_exception=True)
def appointment_new(request):
    if request.method == 'GET':
        StreetList = Street.objects.order_by("name")
        AreaList = Area.objects.filter(is_parent=True)
        context = {"street_list": StreetList, "area_list": AreaList, 'NOMINATIM_URL': NOMINATIM_URL}
        return render(request, 'appointment/appointment_edit.html', context)
    if request.method == "POST":
        contact_name = request.POST['name']
        street = get_object_or_404(Street, name=request.POST['street'])
        house_number = request.POST['house_number']
        timeslot = get_object_or_404(Timeslot, id=request.POST['timeslot'])
        text = request.POST['text']
        phone = request.POST['phone']
        email = request.POST['email']
        area = request.POST['area']
        newAppointment = Appointment(contact_name=contact_name, street=street, house_number=house_number, timeslot=timeslot)
        if text:
            newAppointment.text = text
        if phone:
            newAppointment.phone = phone
        if email:
            newAppointment.email = email
        if area != "None":
            newAppointment.area = Area.objects.get(id=area)
        newAppointment.save()
        return HttpResponseRedirect(reverse('frontend:appointment_map'))

@permission_required("backend.change_appointment", raise_exception=True)
def appointment_overwrite_remove(request, appointment_id):
    Appointment.objects.filter(id=int(appointment_id)).update(area=None)
    return HttpResponse("ok")

@permission_required("backend.add_street", raise_exception=True)
def street_osm_import(request):
    if request.method == "GET":
        plz = request.GET['plz']
        overpass_url = "https://overpass-api.de/api/interpreter"
        overpass_query = f'''
        [out:json][timeout:25];
        area[postal_code="{plz}"];
        way(area)[highway~"^(residential|living_street|secondary|tertiary)$"];
        out;
        '''
        response = requests.get(overpass_url, params={'data': overpass_query})
        raw_data = response.json()
        osm_list = []
        street_list = []
        for street in raw_data['elements']:
            if "name" in street['tags']:
                osm_list.append(street['tags']['name'])
        osm_list = list(dict.fromkeys(osm_list))
        for street in osm_list:
            if Street.objects.filter(name=street).exists():
                continue
            street_list.append(street)
            new_street = Street(name=street)
            new_street.osm_imported = True
            new_street.save()
        context = {"street_list": street_list}
        return render(request, "street/osm_import_confirm.html", context)


@permission_required("backend.view_appointment", raise_exception=True)

WBSAtool/frontend/templates/street/osm_import_confirm.html
{% extends 'base.html' %}

{% block data %}
    <h4>Folgende {{ street_list|length }} Straßen wurden neu hinzugefügt:</h4>
    <ul>
    {% for street in street_list %}
    <li>{{ street }}</li>
    {% endfor %}
    </ul>
{% endblock data %}

WBSAtool/frontend/templates/street/street_bulk_add.html
{% extends 'base.html' %}

{% block titel %}Massenimport: Straßen{% endblock titel %}

{% block data %}
    <form action="{% url 'frontend:street_bulkadd' %}" method="post" class="form-object-edit mt-5">
    {% csrf_token %}
        <div class="field-group my-5">
	        <div class="row mb-3">
                <div class="col">
                    <textarea name="data" cols="30" rows="10" class="font-monospace form-control" id="data"></textarea>
                </div>
            </div>
            <div class="row mb-3">
                Eine Straße pro Zeile
            </div>
        <div class="text-end my-3">
                <button type="submit" name="update" class="btn btn-primary">Speichern</button>
                <a class="btn btn-outline-danger" href="{% url 'frontend:street_list' %}">Abbrechen</a>
        </div>
    </form>

{% endblock data %}

WBSAtool/frontend/templates/street/street_list.html
{% extends 'base.html' %}

{% block titel %}Straßen{% endblock titel %}

{% block data %}

{% if street_list %}
<form method="post" action="{% url 'frontend:street_delete' %}" class="my-md-3">
    {% csrf_token %}
<table class="table">
    <thead class="table-dark">
        <tr>
            <th><input type="checkbox" class="toggle form-check-input" name="select_all"></th>
            <th>Name <div name="filter-col"></div></th>
            <th>Gebiet</th>
            <th>Fahrzeug</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for street in street_list %}
        <tr>
            <td><input type="checkbox" class="toggle form-check-input" value="{{street.id}}" name="select_row"></td>
            <td>{{street.name}}</td>
            <td>{{street.area}}</td>
            <td>{{street.area.parent}}</td>
            <td class="noprint text-end text-nowrap">
                <a class="btn btn-sm btn-warning" href="{% url 'frontend:street_edit' street.id %}" type="button">
                    <i class="bi bi-pencil-square"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

    <div class="btn-group">
        <a href="{% url 'frontend:street_new' %}" class="btn btn-success btn-sm"><i class="bi     bi-plus-circle"  ></i> Neue Straße</a>
        <button type="button" class="btn btn-success btn-sm dropdown-toggle dropdown-toggle-split"    data-bs-toggle="dropdown" aria-expanded="false">
          <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="{% url 'frontend:street_bulkadd' %}">
              <i class="bi bi-stack"></i> Massenimport</a>
          </li>
          <li><a href="#osm_import" class="dropdown-item" data-bs-toggle="modal">
              <i class="bi bi-cloud-download"></i> OSM Import</a>
          </li>
        </ul>
    </div>
    <button class="btn btn-warning btn-sm" formaction="{% url 'frontend:street_bulk_edit' %}" type="submit" name="_edit">Ausgewählte bearbeiten</button>
    <a href="#deleteConfirm" class="btn btn-danger btn-sm" data-bs-toggle="modal"><i class="bi bi-trash3"></i> Ausgewählte Löschen</a>

<div id="deleteConfirm" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Löschen von Straßen</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
            Möchtest du die ausgewählten Straßen wirklich löschen?<br><br>
                <div class="text-danger">Dies löscht auch automatisch <b>ALLE</b> Abholungen, welche in dieser Straße stattfinden. Die Daten können nicht wiederhergestellt werden.</div>
            </div>
            <div class="modal-footer">
                <button type="submit" name="action" value="delete" class="btn btn-danger">Löschen</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
            </div>
        </div>
    </div>
</div>
</form>
<form method="get" action="{% url 'frontend:street_osm_import' %}">
<div id="osm_import" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Straßen aus OpenStreetMap importieren</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
            Bitte gib eine Postleitzahl ein, aus der <i>alle</i> Straßen importiert werden sollen:<br>
                <input class="form-control" type="number" id="plz" name="plz">
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">Hinzufügen</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
            </div>
        </div>
    </div>
</div>
</form>
{% else %}
Keine Straßen angelegt!<br>
<a class="btn btn-primary btn-sm" href="{% url 'frontend:street_bulkadd' %}">
        <i class="bi bi-stack"></i> Massenimport
</a>
{% endif %}
{% endblock data %}