WBSAtool/WBSAtool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('backend.urls')),
    path('', include('frontend.urls'))
]

WBSAtool/backend/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views
from backend import views

app_name = 'backend'
urlpatterns = [
    path('area', views.AreaList.as_view()),
    path('area/<int:pk>', views.AreaDetail.as_view()),
    path('area/<int:pk>/timeslots', views.TimeslotCount.as_view()),
    path('street', views.StreetList.as_view()),
    path('street/<int:pk>', views.StreetDetail.as_view()),
    path('timeslot', views.TimeslotList.as_view()),
    path('timeslot/<int:pk>', views.TimeslotDetail.as_view()),
    path('timeslot/<int:pk>/count', views.singleTimeslotCount.as_view()),
    path('appointment', views.AppointmentList.as_view()),
    path('appointment/<int:pk>', views.AppointmentDetail.as_view()),
    path('api-token-auth/', drf_views.obtain_auth_token)
]

WBSAtool/frontend/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views, auth_views
from .view_collection.area import AreaListView, AreaCreateView, AreaUpdateView
from .view_collection.street import StreetListView, StreetCreateView, StreetUpdateView, StreetBulkUpdateView
from .view_collection.timeslot import TimeslotListView, TimeslotCreateView, TimeslotUpdateView
from .view_collection.appointment import AppointmentListView, AppointmentDispoView, UpdateAppointmentCollected, AppointmentMapView, AppointmentStatsView
from .view_collection.collect import CollectMenu, CollectList

app_name = 'frontend'
urlpatterns = [
    path('', RedirectView.as_view(url='appointment/map'), name='index'),
    path('area/list', AreaListView.as_view(), name='area_list'),
    path('area/new', AreaCreateView.as_view(), name='area_new'),
    path('area/delete', views.area_delete, name='area_delete'),
    path('area/<int:area_id>', views.area_view, name='area_view'),
    path('area/<int:pk>/edit', AreaUpdateView.as_view(), name='area_edit'),
    path('street/list', StreetListView.as_view(), name='street_list'),
    path('street/new', StreetCreateView.as_view(), name='street_new'),
    path('street/edit', StreetBulkUpdateView.as_view(), name='street_bulk_edit'),
    path('street/delete', views.street_delete, name='street_delete'),
    path('street/bulkadd', views.street_bulkadd, name='street_bulkadd'),
    path('street/osm_import', views.street_osm_import, name='street_osm_import'),
    path('street/<int:pk>/edit', StreetUpdateView.as_view(), name='street_edit'),
    path('timeslot/list', TimeslotListView.as_view(), name='timeslot_list'),
    path('timeslot/delete', views.timeslot_delete, name='timeslot_delete'),
    path('timeslot/new', TimeslotCreateView.as_view(), name='timeslot_new'),
    path('timeslot/<int:pk>/edit', TimeslotUpdateView.as_view(), name='timeslot_edit'),
    path('timeslot/suggestion', views.timeslot_suggestion, name='timeslot_suggestion'),
    path('appointment/list', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/dispo', AppointmentDispoView.as_view(), name='appointment_dispo'),
    path('appointment/pdf', views.generate_pdf, name='appointment_pdf'),
    path('appointment/bulk', views.appointment_bulk, name='appointment_bulk'),
    path('appointment/map', AppointmentMapView.as_view(), name='appointment_map'),
    path('appointment/stats', AppointmentStatsView.as_view(), name='appointment_stats'),
    path('appointment/new', views.appointment_new, name='appointment_new'),
    path('appointment/<int:appointment_id>', views.appointment_view, name='appointment_view'),
    path('appointment/<int:appointment_id>/edit', views.appointment_edit, name='appointment_edit'),
    path('appointment/<int:appointment_id>/collected', UpdateAppointmentCollected.as_view()),
    path('appointment/<int:appointment_id>/clearOverwrite', views.appointment_overwrite_remove, name='appointment_clearOverwrite'),
    path('mobile/menu', CollectMenu.as_view(), name='collect_menu'),
    path('mobile/list', CollectList.as_view(), name='collect_list'),
    path('auth/login', auth_views.login_user, name='login'),
    path('auth/logout', auth_views.logout_user, name='logout')
]

WBSAtool/backend/models.py
import requests
from time import sleep
from django.db import models

from backend import logger
from WBSAtool.settings import NOMINATIM_URL

class Area(models.Model):
    name = models.CharField(max_length=200)
    is_parent = models.BooleanField(default=False)
    parent = models.ForeignKey('Area',
                               limit_choices_to={'is_parent': True},
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True)

    def __str__(self):
        return self.name

    def get_timeslots(self):
        if not self.is_parent:
            return []
        logger.error(f"Area {self.name} has no parent, returning empty Timeslot List")
        list = []
        for ts in Timeslot.objects.order_by("date", "time_from"):
            list.append({"area": self,
                "timeslot":ts,
                "appointment_max":ts.appointment_max,
                "count":ts.get_count_per_area(self.id),
                "percentage":ts.get_percentage_per_area(self.id)})
        return list


class Street(models.Model):
    name = models.CharField(max_length=200)
    area = models.ForeignKey('Area',
                             limit_choices_to={'is_parent': False},
                             on_delete=models.SET_NULL,
                             null=True,
                             blank=True)
    osm_imported = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Timeslot(models.Model):
    date = models.DateField()
    time_from = models.TimeField()
    time_to = models.TimeField()
    appointment_max = models.IntegerField()

    def __str__(self):
        return f"{self.date}_{self.time_from}_{self.time_to}"

    def get_count_per_area(self, area_id):
        qs = Appointment.objects.filter(timeslot=self, street__area__parent_id=area_id, area__isnull=True)
        overwrites = Appointment.objects.filter(timeslot=self, area_id=area_id)
        count = (qs | overwrites).count()
        return count

    def get_percentage_per_area(self, area_id):
        percentage = 100 / self.appointment_max * self.get_count_per_area(area_id)
        return percentage

    def get_all_percentage(self):
        list = []
        for area in Area.objects.filter(is_parent=True):
            list.append({"id":area.id, "name":area.name,
                         "percentage":self.get_percentage_per_area(area.id),
                         "count":self.get_count_per_area(area.id)})
        return list


class Appointment(models.Model):
    is_collected = models.BooleanField(default=False)
    area = models.ForeignKey('Area',
                             default=None,
                             on_delete=models.SET_NULL,
                             null=True)
    contact_name = models.CharField(max_length=200)
    street = models.ForeignKey('Street',
                               on_delete=models.CASCADE,
                               null=True)
    house_number = models.CharField(max_length=200)
    timeslot = models.ForeignKey('Timeslot',
                                 on_delete=models.CASCADE,
                                 null=True)
    text = models.CharField(max_length=2000,
                            blank=True,
                            default="")
    phone = models.CharField(max_length=200,
                             blank=True)
    email = models.CharField(max_length=200,
                             blank=True)
    lat = models.CharField(max_length=200,
                             blank=True)
    lon = models.CharField(max_length=200,
                             blank=True)

    def __str__(self):
        return f"{self.contact_name}, {self.street.name} {self.house_number}"

    def save(self, *args, **kwargs):
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"}
        params = {
            "street": f"{self.street} {self.house_number}",
            "city": "Karlsruhe",
            "postalcode": "76227",
            "format": "jsonv2"
        }
        for i in range(1,5):
            try:
                r = requests.get(NOMINATIM_URL, params=params, headers=headers)
                if r.status_code != 200:
                    logger.error(f"encountered Error {r.status_code} while getting data from nominatim")
                    logger.error(r.text)
                    break
                result = r.json()[0]
                if "lat" in result:
                    self.lat = result['lat']
                    self.lon = result['lon']
                    break
                else:
                    logger.info(f"No latitude data in Response, trying again")
                    sleep(1)
            except Exception as e:
                logger.error(e, stack_info=True)
                sleep(1)
        super(Appointment, self).save(*args, **kwargs)

WBSAtool/frontend/forms.py
from django import forms
from backend.models import Area, Street, Timeslot
from django.forms.models import ModelChoiceField

class TimeslotChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.date}, {str(obj.time_from)[:-3]} bis {str(obj.time_to)[:-3]}"


class CollectMenuForm(forms.Form):
    area = forms.ModelChoiceField(queryset=Area.objects.filter(is_parent=True),
                                  label="Fahrzeug",
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    timeslot = TimeslotChoiceField(queryset=Timeslot.objects.all(),
                                   label="Zeitraum",
                                   widget=forms.Select(attrs={'class': 'form-select'}))


class StreetForm(forms.ModelForm):
    class Meta:
        model = Street
        exclude = ["osm_imported"]
        titel = "Straße"
    name = forms.CharField(label="Straßenname",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))


class BulkUpdateStreetForm(forms.Form):
    class Meta:
        titel = "mehrere Straßen bearbeiten"
    area = forms.ModelChoiceField(label="Gebiet",
                                  queryset=Area.objects.filter(is_parent=False),
                                  widget=forms.Select(attrs={'class': 'form-select'}))
    select_row = forms.ModelMultipleChoiceField(queryset=Street.objects.all(),
                                                widget=forms.MultipleHiddenInput)


class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        exclude = []
        titel = "Gebiet"
    name = forms.CharField(label="Name",
                           max_length=200,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_parent = forms.BooleanField(label="Ist ein Fahrzeug",
                                   required=False,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    parent = forms.ModelChoiceField(label="Fahrzeug",
                                    required=False,
                                    queryset=Area.objects.filter(is_parent=True),
                                    widget=forms.Select(attrs={'class': 'form-select'}))


class TimeslotForm(forms.ModelForm):
    class Meta:
        model = Timeslot
        exclude = ["appointment_count", "is_full"]
        titel = "Abholzeitraum"
    date = forms.DateField(label="Datum",
                           widget=forms.DateInput(attrs={'class': 'form-control w-auto', 'type': 'date'}))
    time_from = forms.TimeField(label="Beginn",
                                widget=forms.TimeInput(format='%H:%M',
                                                       attrs={'class': 'form-control w-auto', 'type': 'time'}))
    time_to = forms.TimeField(label="Ende",
                              widget=forms.TimeInput(format='%H:%M',
                                                     attrs={'class': 'form-control w-auto', 'type': 'time'}))
    appointment_max = forms.IntegerField(label="Maximale Abholungen",
                                         widget=forms.TextInput(attrs={'class': 'form-control w-auto'}))

WBSAtool/frontend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>WBSA-Tool</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Lokale Funktionen der Seite -->
    <script type="text/javascript" src="{% static 'wbsa.js'%}"></script>
    <script type="text/javascript" src="{% static 'table_utils.js'%}"></script>
    <link rel="stylesheet" href="{% static 'wbsa.css'%}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a href="/" class="navbar-brand pe-5"><i class="bi bi-tree-fill"></i> WBSA-Tool</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
    {% if user.is_authenticated %}
            <div class="navbar-nav">
                <li class="nav-item dropdown px-3">
                    {% if perm.backend.view_area or perms.backend.view_street or perms.backend.view_timeslot %}
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-database-fill-gear"></i> Datenbank
                    </a>
                    <ul class="dropdown-menu">
                        {% if perms.backend.view_area %}<a href="{% url 'frontend:area_list' %}" class="dropdown-item"><i class="bi bi-map"></i> Gebiete</a>{% endif %}
                        {% if perms.backend.view_street %}<a href="{% url 'frontend:street_list' %}" class="dropdown-item"><i class="bi bi-signpost-split"></i> Straßen</a>{% endif %}
                        {% if perms.backend.view_timeslot %}<a href="{% url 'frontend:timeslot_list' %}" class="dropdown-item"><i class="bi bi-calendar-week"></i> Zeitslots</a>{% endif %}
                    </ul>
                    {% endif %}
                </li>
                {% if perms.backend.view_appointment %}<a href="{% url 'frontend:appointment_list' %}" class="nav-item nav-link px-3"><i class="bi bi-houses"></i> Abholungen</a>{% endif %}
                {% if perms.backend.change_appointment %}<a href="{% url 'frontend:collect_menu' %}" class="nav-item nav-link px-3"><i class="bi bi-truck"></i> Fahrzeug</a>{% endif %}
                <li class="nav-item dropdown px-3">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-info-circle"></i> Infos
                    </a>
                    <ul class="dropdown-menu">
                        <a href="{% url 'frontend:appointment_map' %}" class="dropdown-item"><i class="bi bi-pin-map"></i> Karte</a>
                        <a href="{% url 'frontend:appointment_stats' %}" class="dropdown-item"><i class="bi bi-graph-up"></i> Statistik</a>
                    </ul>
                </li>
            </div>
            <div class="navbar-nav ms-auto">
                {% if perms.backend.add_appointment %}<a href="{% url 'frontend:appointment_new' %}" type="button" class="btn btn-sm btn-success"><i class="bi bi-plus-circle"></i> Neue Abholung</a>{% endif %}
            </div>
            <div class="navbar-nav">
        {% else %}
            <div class="navbar-nav ms-auto">
        {% endif %}
                {% include "registration/user-status-icon.html" %}
            </div>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
{% block container %}
<div class="container-md">
    <div class="px-md-3 py-md-3 my-md-3 bg-light">
        <h1 class="p-3">{% block titel %}{% endblock %}</h1>
        {% block data %}{% endblock data %}
    </div>
</div>
{% endblock container %}
{% else %}
    {% block authform %}{% endblock authform %}
{% endif %}


    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    {% block jsfooter %}{% endblock %}
</body>
</html>

WBSAtool/frontend/templates/bulk_edit.html
{% extends 'base.html' %}

{% block titel %}{{ form.Meta.titel }}{% endblock titel %}

{% block data %}
    <form method="post" class="form-object-edit mt-5">
    {% csrf_token %}
    {% for object in form.initial.id_list %}
        <input type="hidden" name="select_row" value="{{ object }}">
    {% endfor %}
        <div class="field-group my-5">
        {% for field in form %}
            {% if not field.is_hidden %}
	        <div class="row mb-3">
                {{ field.errors }}
                <label for="name" class="col-sm-3 col-form-label text-lg-end">{{ field.label }}</label>
                <div class="col">
                    {{ field }}
                </div>
            </div>
            {% endif %}
        {% endfor %}
        <div class="text-end my-3">
                <button type="submit" name="_save" class="btn btn-primary">Speichern</button>
                <a class="btn btn-outline-danger" href="{% url redirect_to %}">Abbrechen</a>
        </div>
    </form>

{% endblock data %}

WBSAtool/frontend/templates/error_page.html
{% extends 'base.html' %}

{% block titel %}Es ist ein Fehler aufgetreten{% endblock titel %}

{% block data %}

Es ist ein Fehler auf der vorherigen Seite aufgetreten. Die Fehlermeldung:<br>
{{ error_message }}

{% endblock data %}

WBSAtool/frontend/templates/model_edit.html
{% extends 'base.html' %}

{% block titel %}{{ form.Meta.titel }} {% if object %}bearbeiten{% else %}erstellen{% endif %}{% endblock titel %}

{% block data %}
<form method="post" class="form-object-edit mt-5">
{% csrf_token %}
    <div class="field-group my-5">
    {% for field in form %}
        <div class="row mb-3">
            {{ field.errors }}
            <label for="name" class="col-sm-3 col-form-label text-lg-end">{{ field.label_tag }}</label>
            <div class="col">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="text-end my-3">
            <button type="submit" value="Submit" class="btn btn-primary">Speichern</button>
            <a class="btn btn-outline-danger" href="{% url view.redirect_to %}">Abbrechen</a>
    </div>
</form>

{% endblock data %}